#!/usr/bin/env python3
"""Extended idempotency audit for the weekly maintenance workflow.

The unit suite proves idempotency for a handful of deliveries. This script
proves it at the volume a flapping alert produces: the same fingerprint is
delivered 1000 times through the service layer and the run fails unless

* exactly one incident exists at the end,
* every extra delivery was attached and counted as deduplicated,
* the timeline holds one entry per delivery (nothing was dropped).

It also measures the per-delivery ingest latency (end-to-end through
``IncidentService.ingest``, SQLite writes included) and writes the percentiles
to a versioned report. The numbers come from the run, never from a constant.
"""

from __future__ import annotations

import argparse
import json
import platform
import statistics
import sys
import tempfile
import time
from datetime import timedelta
from pathlib import Path
from typing import List, Optional

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from incidentd.config import load_policy  # noqa: E402
from incidentd.models import AlertEvent, utcnow  # noqa: E402
from incidentd.notify import NullNotifier  # noqa: E402
from incidentd.service import IncidentService  # noqa: E402
from incidentd.store import Store  # noqa: E402

DEFAULT_PAYLOAD = "examples/alertmanager/01-firing-checkout-api.json"
DEFAULT_POLICY = "policy/policy.yaml"
DEFAULT_OUT = "reports/weekly-audit.md"


def percentile(samples: List[float], fraction: float) -> float:
    """Nearest-rank percentile; exact for the small sample sizes here."""
    if not samples:
        return 0.0
    ordered = sorted(samples)
    index = max(0, min(len(ordered) - 1, int(round(fraction * len(ordered) + 0.5)) - 1))
    return ordered[index]


def run_audit(alerts: int, payload_path: Path, policy_path: Path) -> dict:
    payload = json.loads(payload_path.read_text(encoding="utf-8"))
    template = payload["alerts"][0]
    labels = dict(template["labels"])
    fingerprint = template["fingerprint"]
    # Keep the delivered alert start recent so the reopen/attach decisions in
    # the service layer see the same clock as the deliveries themselves.
    starts_at = utcnow().replace(microsecond=0) - timedelta(minutes=5)

    policy = load_policy(policy_path)
    with tempfile.TemporaryDirectory() as directory:
        store = Store(Path(directory) / "audit.db")
        service = IncidentService(store, policy, notifier=NullNotifier())
        latencies: List[float] = []
        try:
            for _ in range(alerts):
                event = AlertEvent(
                    fingerprint=fingerprint,
                    status="firing",
                    alertname=template["labels"]["alertname"],
                    labels=labels,
                    annotations=dict(template["annotations"]),
                    starts_at=starts_at,
                    generator_url=template.get("generatorURL"),
                    received_at=utcnow(),
                )
                started = time.perf_counter()
                service.ingest(event)
                latencies.append((time.perf_counter() - started) * 1000.0)

            incidents = store.list_incidents()
            snapshot = store.metrics_snapshot()
            incident = incidents[0]
            timeline = store.list_timeline(incident.id)
        finally:
            store.close()

    return {
        "alerts": alerts,
        "incidents": len(incidents),
        "alerts_received": snapshot.alerts_received,
        "alerts_deduplicated": snapshot.alerts_deduplicated,
        "dedupe_ratio": snapshot.dedupe_ratio,
        "timeline_entries": len(timeline),
        "p50_ms": round(percentile(latencies, 0.50), 3),
        "p95_ms": round(percentile(latencies, 0.95), 3),
        "p99_ms": round(percentile(latencies, 0.99), 3),
        "mean_ms": round(statistics.fmean(latencies), 3),
        "max_ms": round(max(latencies), 3),
    }


def render_report(result: dict, alertmanager_version: Optional[str]) -> str:
    stamp = utcnow().strftime("%Y-%m-%d")
    lines = [
        "# Weekly audit — incidentd",
        "",
        "Generated by `scripts/idempotency_audit.py` from the scheduled workflow",
        "(`.github/workflows/maintenance.yml`). Every number below comes from the run that",
        "produced this commit.",
        "",
        "## Idempotency under volume",
        "",
        "The same fingerprint was delivered %d times through `IncidentService.ingest`"
        % result["alerts"],
        "on a fresh SQLite database.",
        "",
        "| Metric | Value |",
        "| --- | --- |",
        "| Run date (UTC) | %s |" % stamp,
        "| Alerts delivered | %d |" % result["alerts"],
        "| Incidents created | %d |" % result["incidents"],
        "| Alerts counted as deduplicated | %d |" % result["alerts_deduplicated"],
        "| Dedupe ratio | %.4f |" % result["dedupe_ratio"],
        "| Timeline entries recorded | %d |" % result["timeline_entries"],
        "",
        "## Ingest latency (one alert per delivery, SQLite commit included)",
        "",
        "| Percentile | Milliseconds |",
        "| --- | --- |",
        "| p50 | %.3f |" % result["p50_ms"],
        "| p95 | %.3f |" % result["p95_ms"],
        "| p99 | %.3f |" % result["p99_ms"],
        "| mean | %.3f |" % result["mean_ms"],
        "| max | %.3f |" % result["max_ms"],
        "",
        "## Environment",
        "",
        "| Item | Value |",
        "| --- | --- |",
        "| Python | %s |" % platform.python_version(),
        "| Platform | %s |" % platform.platform(),
        "| Alertmanager release checked | %s |" % (alertmanager_version or "not queried"),
        "",
    ]
    return "\n".join(lines)


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--alerts", type=int, default=1000)
    parser.add_argument("--payload", default=DEFAULT_PAYLOAD)
    parser.add_argument("--policy", default=DEFAULT_POLICY)
    parser.add_argument("--out", default=DEFAULT_OUT)
    parser.add_argument("--alertmanager-version", default=None)
    args = parser.parse_args(argv)

    result = run_audit(args.alerts, Path(args.payload), Path(args.policy))

    problems = []
    if result["incidents"] != 1:
        problems.append("expected exactly 1 incident, got %d" % result["incidents"])
    if result["alerts_deduplicated"] != args.alerts - 1:
        problems.append(
            "expected %d deduplicated deliveries, got %d"
            % (args.alerts - 1, result["alerts_deduplicated"])
        )
    if result["timeline_entries"] < args.alerts:
        problems.append(
            "timeline has %d entries for %d deliveries" % (result["timeline_entries"], args.alerts)
        )

    report = render_report(result, args.alertmanager_version)
    if problems:
        report += "\n## Result\n\nFAILED — " + "; ".join(problems) + "\n"

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(report, encoding="utf-8")

    for key, value in result.items():
        print("%-20s %s" % (key, value))
    print("\nreport written to %s" % out)

    if problems:
        for problem in problems:
            print("audit: %s" % problem, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
